# Generated by Django 4.2.1 on 2023-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='css_view',
            field=models.CharField(default='none', max_length=32),
        ),
    ]
